# mosquitto.conf
# Listen on port 1883 for all network interfaces
listener 1883 0.0.0.0

# Allow anonymous access for development 
allow_anonymous true

# Enable persistence to store data on disk
persistence true
persistence_location /mosquitto/data/

# Log messages to the console for debugging
log_dest stdout

# this is a docker internal path to save the password filefrom the host
#password_file /mosquitto/config/passwd
