
services:
  # Service name: mqtt-broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: airguard-mosquitto

    # ports Mapping: <Laptop Port> : <Container Port>
    # This allows RPI or MQTT Explorer to find the broker
    ports:
      - "1883:1883" # MQTT protocol
      - "9001:9001" # WebSockets

    # Volumes: we map local config file into the container's expected path
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    #Network: keep microservices in the same virtual room
    networks:
      - airguard-network

    # Auto-restart: if the broker crashes, it will try to restart
    restart: unless-stopped

  sensor-service:
    build: .
    container_name: airguard-sensor
    command: ["python", "main_sensor.py"]
    depends_on:
      - mosquitto
    environment:

      - MQTT_BROKER=mosquitto
    networks:
      - airguard-network
    restart: unless-stopped

  adaptor-service:
    build: .
    container_name: airguard-adaptor
    command: ["python", "main_adaptor.py"]
    depends_on:
      - mosquitto
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_USER=iot_admin
      - MQTT_PASSWORD=airguard2026
    networks:
      - airguard-network
    restart: unless-stopped
    volumes:
      - ./components/adaptor/config.yaml:/app/config.yaml:ro

  dashboard-service:
    build:
      context: ./dashboard_service
    container_name: airguard-dashboard
    ports:
      - "8501:8501"
    environment:
      - CATALOG_SERVICE_URL=http://host.docker.internal:8001
      - PREDICTION_SERVICE_URL=http://host.docker.internal:8003
      - DECISION_SERVICE_URL=http://host.docker.internal:8002
      - ADAPTOR_SERVICE_URL=http://host.docker.internal:8000
      - ADAPTOR_CONFIG_PATH=/app/adaptor_config.yaml
      - DEFAULT_ROOM_ID=room1
    volumes:
      - ./components/adaptor/config.yaml:/app/adaptor_config.yaml:ro
    networks:
      - airguard-network
    restart: unless-stopped

  telegram-notifier:
    build:
      context: ./telegram_notifier
    container_name: airguard-telegram
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_ALERT_TOPIC=alert/#
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - TELEGRAM_BOT_NAME=AirGuard Alerts
    networks:
      - airguard-network
    restart: unless-stopped

networks:
  airguard-network:
    driver: bridge